main:
  secret_key_base: "rake secret"
  domain: localhost:2000
  title: Dobroserver [dev]

mailer:
  from: "'Notifications Fairy' <notifications_fairy@dobroserver.ru>"
  to:   "ksevelyar@dobroserver.ru"
