#!/bin/sh

### BEGIN INIT INFO
# Provides:          unicorn_dobroserver
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the unicorn web server
# Description:       starts unicorn using start-stop-daemon
### END INIT INFO

APP_PATH=/data/projects/dobroserver
RAILS_ROOT=$APP_PATH/current

PID=$APP_PATH/shared/tmp/pids/unicorn.pid
OLD_PID="$PID.oldbin"

CONFIG=$RAILS_ROOT/config/unicorn.rb

ENV=production
USER=www-data

bundle="/usr/local/rvm/bin/default_bundle"
CMD="$bundle exec unicorn -E $ENV -c $CONFIG -D"

cd $RAILS_ROOT || exit 1

sig () {
  test -s "$PID" && kill -$1 $(cat $PID)
}

oldsig () {
  test -s $OLD_PID && kill -$1 $(cat $OLD_PID)
}

case $1 in
  start)
    sig 0 && echo >&2 "Already running" && exit 0
    su $USER -c "$CMD"
    ;;
  stop)
    sig QUIT && exit 0
    echo >&2 "Not running"
    ;;
  force-stop)
    sig TERM && exit 0
    echo >&2 "Not running"
    ;;
  restart|reload)
    sig HUP && echo reloaded OK && exit 0
    echo >&2 "Couldn't reload, starting '$CMD' instead"
    su $USER -c "$CMD"
    ;;
  upgrade)
    sig USR2 && exit 0
    echo >&2 "Couldn't upgrade, starting '$CMD' instead"
    su $USER -c "$CMD"
    ;;
  rotate)
    sig USR1 && echo rotated logs OK && exit 0
    echo >&2 "Couldn't rotate logs" && exit 1
    ;;
  *)
    echo >&2 "Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
    exit 1
    ;;
esac
